[package]
name = "flux-platform-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
flux-engine-core = { path = "../../engine-core" }
flux-pcap-generator = { path = "../../test-utils/pcap-generator" }
anyhow = "1.0"
rand = "0.8"

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = "0.4"
