name: CI

on:
  push:
    branches: [ main, "feat/*" ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libbpf-dev libxdp-dev
        
    - name: Build
      run: cargo build --workspace --verbose
      
    - name: Run Unit Tests
      run: cargo test --workspace --verbose
      
    - name: Run Integration Tests (Cucumber)
      run: cd flux-fingerprint-engine && cargo run -p flux-integration-tests --verbose
